<?php

function uky_email_signature_generator_init() {

  drupal_add_js(
    array(
      'uky_email_signature' => array(
        'modulePath' => drupal_get_path(
          'module',
          'uky_email_signature'
        )
      )
    ),
    'setting'
  );


  //HEAD
  //    print current_path();
  if (current_path() == 'branding-tools/email-signature-generator'){
    $modulePath = drupal_get_path('module', 'uky_email_signature');
    drupal_add_js('//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.js', 'external');
    drupal_add_js($modulePath.'/assets/js/vendor/clipboard.js');
    drupal_add_js($modulePath.'/assets/js/vendor/chosen/chosen.jquery.min.js');

    drupal_add_css($modulePath.'/assets/js/vendor/chosen/chosen.min.css');
    drupal_add_css($modulePath.'/semantic/dist/semantic.min.css');
    drupal_add_css($modulePath.'/assets/css/homepage.css');

    //footer
    drupal_add_js($modulePath.'/semantic/dist/semantic.min.js', array('scope' => 'footer'));
    drupal_add_js($modulePath.'/assets/js/main.js', array('scope' => 'footer'));
    drupal_add_js($modulePath.'/assets/js/variables.js', array('scope' => 'footer'));
  };
}



/**
 * Implements hook_permission().
 *
 */
function uky_email_signature_generator_permission() {
  return array(
    'access email signature generator page' => array(
      'title' => t('Access email signature generator'),
      'description' => t('Allow users to access the email signature generator page'),
    ),
  );
}


/**
 * Implements hook_menu().
 *
 * @see hook_menu()
 * @see menu_example
 */
function uky_email_signature_generator_menu() {

  $items['branding-tools/email-signature-generator'] = array(
    'title' => 'Email Signature Generator',
    'page callback' => 'page_email_signature_generator',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );


  $items['branding-tools/email-signature-generator/code'] = array(
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'delivery callback' => 'page_email_signature_generator_html',
  );

  $items['branding-tools/email-signature-generator/code-simplified'] = array(
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'delivery callback' => 'page_email_signature_generator_html_simplified',
  );

  return $items;
}


function page_email_signature_generator() {

  ob_start();
  include 'form.php';
  $output = ob_get_clean();

  return array('#markup' => '<p>' . $output . '</p>');
}

function page_email_signature_generator_html() {

  ob_start();
  include 'dist/code.php';
  $output = ob_get_clean();
  print $output;

  drupal_page_footer();
};


function page_email_signature_generator_html_simplified() {

  ob_start();
  include 'dist/code-simplified.php';
  $output = ob_get_clean();
  print $output;

  drupal_page_footer();
};





/**
 * Implements hook_system_info_alter()
 * Adds a new "tray" region to the current theme
 */
function uky_email_signature_generator_system_info_alter(&$info, $file, $type){
  //    global $theme;
  //
  //    // If non-default theme configuration has been selected, set the custom theme.
  //    $custom_theme = isset ($theme) ? $theme : variable_get('theme_default', 'bartik');
  //
  //    if ($file->name == $custom_theme){
  //        $info['regions'] = array_merge($info['regions'],  array('email-instructions' => t('Email Sig Instructions')));
  //    }

  if ($type == 'theme') {
    $info['regions']['email_instructions'] = t('Email Instructions');
  }

}
