<?php
/**
 * Implements hook_theme().
 */
function uky_email_signature_generator_theme($existing, $type, $theme, $path) {
  return [
    'uky_email_signature_generator_form' => [
      'path' => $path . '/templates',
      'template' => 'email-signature-generator-page',
      'variables' => [
        'form' => NULL,
        'data' => [
          'first_name' => 'John',
          'last_name' => 'Smith',
          'credentials' => 'Ph.D',
          'pronouns' => '',
          'position_title' => 'Director',
          'department_unit' => 'Department/Unit',
          'sub_unit' => 'Sub-Unit/Team',
          'address' => '123 Main St.',
          'city_state_zip' => 'Lexington, KY 40506',
          'phone' => '859.555.5555',
          'email' => 'john.smith@example.com',
        ]
      ],
    ],
    'signature_result' => [
      'path' => $path . '/templates',
      'template' => 'signature',
      'variables' => [
        'form' => NULL,
        'data' => [
          'first_name' => NULL,
          'last_name' => NULL,
          'credentials' => NULL,
          'pronouns' => NULL,
          'position_title' => NULL,
          'department_unit' => NULL,
          'sub_unit' => NULL,
          'address' => NULL,
          'city_state_zip' => NULL,
          'phone' => NULL,
          'email' => NULL,
        ]
      ],
    ]
  ];
}

/**
 * Implements hook_menu().
 *
 * @see hook_menu()
 * @see menu_example
 */
function uky_email_signature_generator_menu() {
  // TODO evaluate use/need for this hook
  $items['branding-tools/email-signature-generator'] = array(
    'title' => 'Email Signature Generator',
    'page callback' => 'page_email_signature_generator',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );

  $items['branding-tools/email-signature-generator/code'] = array(
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'delivery callback' => 'page_email_signature_generator_html',
  );

  $items['branding-tools/email-signature-generator/code-simplified'] = array(
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'delivery callback' => 'page_email_signature_generator_html_simplified',
  );

  return $items;
}
